
## Code for analysis of SPLiTseq mRNA / amplicon data
## This code expects seurat objects matching the format of those output by the
##    STEP1_AAV_SPLiTseq_MultiAssayIntegration_v1.0.R script

## This script will require customization based on the dataset being analyzed.
suppressPackageStartupMessages({
  library(glmGamPoi)
  library(harmony)
  library(readr)
  library(cowplot)
  library(details)
  library(viridis)
  library(scCustomize)
  library(patchwork)
  library(Seurat)
  library(tidyseurat)
  library(dplyr)
  library(tidyverse)
  
  # Doublet finder dependencies
  library(Matrix)
  library(fields)
  library(KernSmooth)
  library(ROCR)
  library(parallel)
  library(remotes)
  ## Use the lines below to install DoubletFinder if needed.
  ##    EDIT: On some computers this requires manually changing the file download method. Otherwise, you may get
  ##              a 'cannot open URL' message. The options() code below fixed it.
  ##options(download.file.method = "wininet")
  ##remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
  library(DoubletFinder)
  
  ## Seurat v5 documentation says they use presto to dramatically improve the speed of DE cluster
  ##    analysis. You can install it using the code below:
  ##install.packages("devtools")
  #options(download.file.method = "wininet") ## You may need to run this line again, even if you ran it already for DoubletFinder
  ##devtools::install_github("immunogenomics/presto")
  library(presto)
  
  ## Installing Azimuth. This package isn't used until the Step3 Cell Type Annotation but it may be easier to install at this
  ##    stage with the other GitHub based packages.
  #if (!requireNamespace('remotes', quietly = TRUE)) {
  #  install.packages('remotes')
  #}
  #options(download.file.method = "wininet") ## You need to run this line again, even if you ran it already for DoubletFinder
  #remotes::install_github('satijalab/azimuth', ref = 'master')
  library(Azimuth)
  
  ## Other
  library(officer)
  library(rvg)
  library(writexl)
  library(ggplotify)
  
})

## Depending on your computer you may have to increase the allowable size of global variables that can be
##    passed on to certain functions (specifically some functions in the future() package that 
##    Seurate uses) or I run into errors with some of the dimensionality reductions.
options(future.globals.maxSize = 1000 * 1024^2)

## This toggle will control whether PowerPoint files with summary figures related to the various sections
##    of the code are created and saved.
save_figures <- FALSE

## These toggles control whether the seurat objects and filtering stats tables are saved as RDS files.
save_seurat_objects <- FALSE
save_stat_tables <- FALSE

## This variable controls whether doublet finder will be run on the QC filtered seurat object
run_doublet_finder <- TRUE

## This variable will determine if the data is run through rpca and harmony integration
run_integrations <- TRUE

## Use this variable to tell the code where your seurat.rds files are located. They don't need to be the only files
##    in that folder, but they do need to have seurat in the name (and there can't be files you don't want analyzed
##    that contain seurat in their names).
## NOTE: the code will be looking for lowercase seurat in the filenames. You can safely use Seurat (uppercase) in 
##       file/folder names that you don't want analyzed.
data_dir <- "C:/<Path_to_Your_Directory>/SPLiTseq_Data/seurat/"

## Tag that will be added to the save file names for outputs of this script
data_prefix <-  "My_Project_Name"

## Directory where figures created by this script will be saved
figure_dir <- "C:/<Path_to_Your_Directory>/SPLiTseq_Data/seurat/Figures"
##  Creating the figure_dir if it does not already exist
if (!dir.exists(figure_dir)) {dir.create(figure_dir, showWarnings = TRUE, recursive = FALSE, mode = "0777")}

## Directory where processed seurat objects created by this script will be saved
##    If you want to save the figures and seurat objects to the same directory, just use the same directory for both
##    of these variables.
data_output_dir <- "C:/<Path_to_Your_Directory>/SPLiTseq_Data/seurat/STEP2_Seurat_Objects"
##  Creating the data_output_dir if it does not already exist
if (!dir.exists(data_output_dir)) {dir.create(data_output_dir, showWarnings = TRUE, recursive = FALSE, mode = "0777")}



## This code can attempt to quantitatively determine an appropriate number of principle components to use
##    as input for functions that use PCA data as input. It will calculate this value by running the following calculations
##    on the PCA data generated by Seurat's RunPCA() function:
##    Method A) The code will identify the lowest number PC among the PCs that explain >= PCs_CumulPctVar_Threshold 
##                of the cumulative variance that itself explains < PCs_AbsVar_Threshold variance
##              Or, in less technical terms, the code will identify the minimal set of principle components that explain at least
##                X % of the total variance, then check to see if any of the PCs not included in this set actually explain a
##                fairly large amount of variance. 
##              For example, let's say you set the cumulative variance threshold to 80% and the absolute variance threshold to 5%, and
##                you have a dataset with 15 PCs. The code would figure out that, e.g., PCs 1:10 explain 80% of the total variance, but
##                PC 11 explains 7% of the remaining variance while PCs 12-15 each explain less than 5% each. So, Method A here
##                would return PCs 1:11 as the recommended set to use for dimensional reduction.
##    Method B) This method attempts to identify the point of diminishing returns in the PCA reduction by using an 
##                algebraic short-cut to estimate the location of the 'elbow' in an ElbowPlot. The code will calculate the difference
##                in variance explained between each sequential set of PCs (i.e., PC1 - PC2, PC2 - PC3, etc.) and identify the highest
##                PC after which the difference in variance between all subsequent PCs is < PC_DeltaVar_Threshold
##              So basically, we are identifying the PC after which additional PCs fail to explain much more variance than the preceding PCs.
##    The code will then compare the PC # determined by Method A and Method B and use the lower of the two.


## If you would prefer to define the number of PCs for clustering functions yourself
##    instead of using mathematical calculation of optimal PCs, set this
##    use_automated_nPCs_calc toggle to false and enter your desired max PCs in the
##    nPCs_for_cluster_fxns variable.
## If use_automated_nPCs_calc is set to TRUE, the value in nPCs_for_cluster_fxns will be
##    over-written later in the code.
use_automated_nPCs_calc <- TRUE
nPCs_for_cluster_fxns <- 20

## Below are the variables used to set thresholds for the Method A and Method B calculations described above.
## NOTE: The following variables take whole, not fractional, % values (i.e., for a value of 80%, you would enter 80, not 0.8)

## Method A Variables
PCs_CumulPctVar_Threshold <- 80
PCs_AbsVar_Threshold <- 5

## Method B Variable
PC_DeltaVar_Threshold <- 0.1



## The principle components used for clustering functions will be tracked throughout the script
##    and the information will be included in the RunInfoAndStats output file.
if (use_automated_nPCs_calc) {
  nPCs_for_cluster_tracker <- c()
} else {
  nPCs_for_cluster_tracker <- paste0('User Defined nPCs Value = ',as.character(nPCs_for_cluster_fxns))
}


## Number of features to select as top variable features when running FindVariableFeatures()
##    The default value for Seurat v5 is 2000.
nVariableFeatures <- 3500

## Value for the resolution variable used in Seurat's FindClusters() function. Higher values
##    will result in more clusters
FindClusterResolution <- 0.2


variables_to_regress <- c('percent_mito','nCount_RNA')


##################################################################
##
##  STEP 0 - Find, Load, Merge and Clean Datasets
##
##  Identify data files to be analyzed
##  Load the relevant seurat.rds objects
##  Merge the different seurat datasets into a single seurat object
##  Remove cells that are not properly linked to meta.data
##
##################################################################

files <-list.files(path = data_dir, pattern = 'seurat') %>%
  as_tibble() %>%
  dplyr::rename(name = value)

## This variable stores a list of the sublibraries being analyzed. It is used
##    as a convenient way to reference this info later in the script
sublibrary_IDs <- str_remove(files$name, "_seurat.rds")

seurat.list <- lapply(paste0(data_dir,files$name), readRDS)

seurat_merged <- Merge_Seurat_List(seurat.list, add.cell.ids = sublibrary_IDs)
rm(seurat.list)

## Run this line if you want to keep a copy of the raw merged seurat object so 
##    you can restore it without having to re-run the above code.
#seurat_merged_orig <- seurat_merged


## Merging creates Layers that correspond to the different sublibraries
## At the moment, you can't re-name these layers without using weird workarounds
## If for some reason you need to know the names of the counts layer corresponding
##    to a given sublibrary, you can use the following code. The Layers() command
##    will give you the names of all the counts layers. You can then plug in one of
##    those names (e.g., counts.1.1) into the code below to identify the sublibrary
##    it corresponds to.
#Layers(seurat_merged)
#colnames(seurat_merged[['RNA']]$counts.1.1[,c(1:10)])



##############################################################################
##
##   ADD COLUMN(s) WITH TRANSDUCTION STATUS (this is going to be TRUE/FALSE)

## This metadata will be useful for some later plotting functions and also for
##    tracking stats for AAV2 and AAV9 transduced cells during the various filtering stages.

## This is more complicated to do with a multi-assay object, particularly
##    if we want to be able to run it without having to hard-code the
##    assay names.
meta_pull <- seurat_merged@meta.data
for (i in 2:length(Seurat::Assays(seurat_merged))) {
  assay_name <- Seurat::Assays(object = seurat_merged)[i]
  assay_metric <- paste0('nCount_',assay_name)
  transduction_status <- seurat_merged@meta.data[,assay_metric] > 0
  serotype <- str_split(assay_name,pattern='_')[[1]][1]
  new_metric <- paste0(serotype,'_transduction')
  meta_pull <- add_column(meta_pull, '{new_metric}' := transduction_status)
}
seurat_merged@meta.data <- meta_pull
rm(meta_pull)











#######################################################################
##
##  Remove cells without corresponding meta data
##

## I've attempted to write a function here that will work with any dataset without requiring
##    user input.
## This is a reasonably robust generic solution for identifying artifact cells.
##    However, this method will fail if there are empty entries in the first non-Barcode 
##    column of the cell_meta csv file loaded in the STEP1 script. 

seurat_merged@meta.data$ArtifactCells <- is.na(seurat_merged@meta.data[,grep('nFeature_RNA',colnames(seurat_merged@meta.data))+1])


##  This code creates a data frame containing information on cell counts for each 
##      sublibrary before and after filtering
pre_filter_cell_counts <- as.data.frame(table(seurat_merged$orig.ident))
artifact_cell_counts <- as.data.frame(table(seurat_merged$orig.ident[seurat_merged$ArtifactCells==TRUE]))

## Note: sublibrary_IDs is created at the top of the script
artifact_filtering_stats <- data.frame(matrix(nrow=3,ncol=(length(sublibrary_IDs)+1)))
colnames(artifact_filtering_stats) <- c('Metric',sublibrary_IDs)
artifact_filtering_stats$Metric <- c('nCells_PreArtifactFilter','n_ArtifactCells','nCells_PostArtifactFilter')

## First, I'm calculating the number of cells pre- and post-filtering for each sublibrary
for (i in 2:ncol(artifact_filtering_stats)) {
  artifact_filtering_stats[1,i] <- pre_filter_cell_counts[(i-1),2]
  artifact_filtering_stats[2,i] <- artifact_cell_counts[(i-1),2]
  artifact_filtering_stats[3,i] <- pre_filter_cell_counts[(i-1),2] - artifact_cell_counts[(i-1),2]
}

## Now I'm handling the much more difficult task of counting the number of transduced cells
##    for each sublibrary. This gets complicated because I've written everything so that it will work 
##    regardless of the number or identity of the serotypes present in the data.
metadata <- seurat_merged@meta.data

for (x in 2:length(Seurat::Assays(seurat_merged))) {
  assay_name <- Seurat::Assays(object = seurat_merged)[x]
  serotype <- str_split(assay_name, pattern = "_")[[1]][1]
  metadata_column_name <- paste0(serotype,'_transduction')
  assay_stats <- data.frame(matrix(nrow=3,ncol=ncol(artifact_filtering_stats)))
  colnames(assay_stats) <- colnames(artifact_filtering_stats)
  assay_stats$Metric[1] <- paste0('nCells_PreArtifactFilter_',serotype)
  assay_stats$Metric[2] <- paste0('n_ArtifactCells_',serotype)
  assay_stats$Metric[3] <- paste0('nCells_PostArtifactFilter_',serotype)
  
  for (i in 1:length(sublibrary_IDs)) {
    metadata_pull <- metadata[metadata$orig.ident == sublibrary_IDs[i],]
    prefilter_stats <- as.data.frame(table(metadata_pull[,metadata_column_name]))
    assay_stats[1,i+1] <- prefilter_stats[2,2]
    assay_stats[2,i+1] <- sum(metadata_pull$ArtifactCells[metadata_pull[,metadata_column_name]==TRUE])
    assay_stats[3,i+1] <- assay_stats[1,i+1] - assay_stats[2,i+1]
  }
  
  artifact_filtering_stats <- rbind(artifact_filtering_stats,assay_stats)
}

artifact_filtering_stats$Totals <- rowSums(artifact_filtering_stats[,c(2:ncol(artifact_filtering_stats))])



#######################################################
##
## Actual filtering of artifacts
##

Idents(seurat_merged) <- 'ArtifactCells'
seurat_merged <- subset(seurat_merged, idents = "FALSE")
Idents(seurat_merged) <- 'orig.ident'
seurat_merged@meta.data$ArtifactCells <- NULL





##################################################################
##
##  STEP 1 - QC Metric Calculations and Low-Quality Cell Filtering
##
##  While similar QC metrics will be run on any dataset, the filters and thresholds
##      used to define and filter out low-quality cells will need to be determined
##      and set on a case-by-case basis.
##
##################################################################

## This function adds a Cell_Complexity column to the meta.data. Cell Complexity is
##    a measurement of how many genes are detected vs total UMI counts. A low complexity
##    value generally indicates that a cell had low gene detection but comparatively high
##    UMI counts in these detected genes. As UMI counts increase, that should mean our
##    coverage of a cell increases, which in turn should mean that we will detect more genes.
##    If UMI counts are high relative to the number of genes detected, then something is
##    wrong (e.g., the cell was undergoing apoptosis and shutting down gene transcription).
##    So, it's a good idea to filter out low complexity cells.
seurat_merged <- Add_Cell_Complexity_Seurat(seurat_merged)

## This function adds columns to the meta.data containing info on the % of detected
##    genes that are mitochondrial or ribosomal.
## Low-quality / dying cells often exhibit high levels of mitochondrial contamination,
##    so this is a commonly used metric for cell filtering
## The Seurat vingette uses a 5% filter; The original version of this code was using
##    a less stringent 10% filter.
seurat_merged <- Add_Mito_Ribo_Seurat(seurat_merged, species =  "human")



###################
########################################################
##
##  QC Metric Visualization

##  The following code generates violin plots showing:
##      1) Number of genes (nFeature) detected
##      2) Number of UMIs (nCount)
##      3) Cell Complexity


##  These variables represent the primary metrics that the data will be filtered based on. 
##      I've set up the code so that subsequent functions use the values stored in these variables.
##      That way everything is consistent and you don't end up with different plots and functions
##      using different values for these metrics.
##  So, the general workflow is to set these values. Run the QC plots to see how they fit the data.
##      adjust the values as necessary until you are happy with the filtering parameters. Then you
##      can run the code that creates a PowerPoint output for the QC metrics and proceed with the
##      actual filtering.
##  If you end up not wanting to use one of these metrics in the final filtering, you have two options:
##      1) Set the value so high or low that it doesn't actually filter any cells from your data
##      2) Change the code in the filter variable defined at the end of this QC block to remove the
##            entry associated with the variable you aren't using.

## Gene count thresholds
nFeature_low <- 250
nFeature_high <- 7000

## UMI count thresholds
nCount_low <- 400
nCount_high <- 15000

## Complexity threshold
complexity_cutoff <- 0.9

## Mitochondrial gene expression threshold
mito_threshold <- 0.1


## QC Plots and Threshold Visualization

## I have this set up to plot these stats for each sublibrary separately (sublibrary identity is contained
##    in the orig.ident variable in the meta.data of this dataset). If you want to examine different subsets
##    you can adjust the group.by argument, or leave it out if you want to see all cells plotted together.

## I found it most convenient to not save the plots to a variable at this stage, but you can uncomment the code
##    following these lines if you'd prefer to create the ggplot variables.
## Following the filtering step there is code to plot and save pre- and post-filtering QC graphs to a PowerPoint
##    file. It's intended to be run once you've finalized your filtering parameters. If you want to save multiple
##    sets of pre- and post-filter graphs showing the results of different filtering parameters, then just make sure
##    that you change the line of code that creates the PowerPoint file name within the plot saving code chunk.

QC_Plots_Genes(seurat_object = seurat_merged, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
QC_Plots_UMIs(seurat_object = seurat_merged, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
QC_Plots_Complexity(seurat_object = seurat_merged, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
QC_Plot_UMIvsGene(seurat_object = seurat_merged,high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
                                    high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")

#nFeature_violin <- QC_Plots_Genes(seurat_object = seurat_merged, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
#nCount_violin <- QC_Plots_UMIs(seurat_object = seurat_merged, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
#complexity_violin <- QC_Plots_Complexity(seurat_object = seurat_merged, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
## Run this code to visualize the data in R as a single figure.
#wrap_plots(nFeature_violin, nCount_violin, complexity_violin, ncol = 3)

#UMIvsGene_Plot <- QC_Plot_UMIvsGene(seurat_object = seurat_merged,high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
#                  high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")


## Here's some code that will attempt to mathematically calculate thresholds using 
##    Median Absolute Deviations (MAD), specifically 3 MADs. The values I got weren't very helpful for the
##    Retina dataset
## Actually, this whole thing is probably more of a pain than it is worth. I'm pretty sure the library(scater) 
##    package that the isOutlier function is part of ends up loading another package that has some functions
##    with the same names as Seurat functions, which ends up causing annoying problems.
#nMAD_thresh_nFeatures <- isOutlier(seurat_merged$nFeature_RNA, nmad=3, log=TRUE)
#attr(nMAD_thresh_nFeatures, "thresholds")
#nMAD_thresh_nCounts <- isOutlier(seurat_merged$nCount_RNA, nmad=3, log=TRUE)
#attr(nMAD_thresh_nCounts, "thresholds")




#####################
##################################################
##
##  Filtering the Seurat Object
##
##################################################
#####################

##  These are a critical couple lines of code that will perform the actual filtering of the
##      seurat object data based on the parameters that you've defined.
filter <- !(seurat_merged$nFeature_RNA < nFeature_low | seurat_merged$nFeature_RNA > nFeature_high | 
              seurat_merged$nCount_RNA < nCount_low | seurat_merged$nCount_RNA > nCount_high |
              seurat_merged$percent_mito > mito_threshold | 
              seurat_merged$log10GenesPerUMI < complexity_cutoff)

seurat_filtered <- seurat_merged[,filter]



## Run this code if you'd like to visualize the data post-filtering
##    After the code that calculates the cell filtering stats (below) is a chunk of code that will 
##    plot and save pre- and post-filtering versions of these QC control figures into a PowerPoint file.
QC_Plots_Genes(seurat_object = seurat_filtered, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
QC_Plots_UMIs(seurat_object = seurat_filtered, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)
QC_Plots_Complexity(seurat_object = seurat_filtered, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0)

QC_Plot_UMIvsGene(seurat_object = seurat_filtered,high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
                  high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")




##################################################
##
##  Calculate Cell Filtering Stats

##  This code creates a data frame containing information on cell counts for each 
##      sublibrary before and after filtering
pre_filter_cell_counts <- as.data.frame(table(seurat_merged$orig.ident))
post_filter_cell_counts <- as.data.frame(table(seurat_filtered$orig.ident))

## Note: sublibrary_IDs is created at the top of the script
QC_filtering_stats <- data.frame(matrix(nrow=3,ncol=(length(sublibrary_IDs)+1)))
colnames(QC_filtering_stats) <- c('Metric',sublibrary_IDs)
QC_filtering_stats$Metric <- c('nCells_PreFilter','nCells_PostFilter','nCells_Filtered')

## First, I'm calculating the number of cells pre- and post-filtering for each sublibrary
for (i in 2:ncol(QC_filtering_stats)) {
  QC_filtering_stats[1,i] <- pre_filter_cell_counts[(i-1),2]
  QC_filtering_stats[2,i] <- post_filter_cell_counts[(i-1),2]
  QC_filtering_stats[3,i] <- pre_filter_cell_counts[(i-1),2] - post_filter_cell_counts[(i-1),2]
}

## Now I'm handling the much more difficult task of counting the number of transduced cells
##    for each sublibrary. This gets complicated because I've written everything so that it will work 
##    regardless of the number or identity of the serotypes present in the data.
prefilter_metadata <- seurat_merged@meta.data
postfilter_metadata <- seurat_filtered@meta.data
for (x in 2:length(Seurat::Assays(seurat_merged))) {
    assay_name <- Seurat::Assays(object = seurat_merged)[x]
    serotype <- str_split(assay_name, pattern = "_")[[1]][1]
    metadata_column_name <- paste0(serotype,'_transduction')
    assay_stats <- data.frame(matrix(nrow=3,ncol=ncol(QC_filtering_stats)))
    colnames(assay_stats) <- colnames(QC_filtering_stats)
    assay_stats$Metric[1] <- paste0('nCell_PreFilter_',serotype)
    assay_stats$Metric[2] <- paste0('nCell_PostFilter_',serotype)
    assay_stats$Metric[3] <- paste0('nCell_Filtered_',serotype)
    
  for (i in 1:length(sublibrary_IDs)) {
      prefilter_metadata_pull <- prefilter_metadata[prefilter_metadata$orig.ident == sublibrary_IDs[i],]
      postfilter_metadata_pull <- postfilter_metadata[postfilter_metadata$orig.ident == sublibrary_IDs[i],]
    
      prefilter_stats <- as.data.frame(table(prefilter_metadata_pull[,metadata_column_name]))
      assay_stats[1,i+1] <- prefilter_stats[2,2]
      postfilter_stats <- as.data.frame(table(postfilter_metadata_pull[,metadata_column_name]))
      assay_stats[2,i+1] <- postfilter_stats[2,2]
      assay_stats[3,i+1] <- prefilter_stats[2,2] - postfilter_stats[2,2]
  }
    
  QC_filtering_stats <- rbind(QC_filtering_stats,assay_stats)
}

QC_filtering_stats$Totals <- rowSums(QC_filtering_stats[,c(2:ncol(QC_filtering_stats))])





###################
############################################
##  Run this code to output a PowerPoint file with the pre- and post-filter QC plots
##

if (save_figures) {
  
  figures_PP <- read_pptx()
  windowsFonts("Times" = windowsFont("Times"))
  text_mod <- fp_text_lite(font.size=22, color='black')
  
  nFeature_title <- paste0('Pre-Filter Genes Per Nucleus','\n','cut-offs ',nFeature_low,'-',nFeature_high)
  nFeature_violin <- QC_Plots_Genes(seurat_object = seurat_merged, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nFeature_title)
  vectorized_plot <- rvg::dml(ggobj = nFeature_violin)
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_left())
  
  nFeature_title <- paste0('Post-Filter Genes Per Nucleus','\n','cut-offs ',nFeature_low,'-',nFeature_high)
  nFeature_violin <- QC_Plots_Genes(seurat_object = seurat_filtered, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nFeature_title)
  vectorized_plot <- rvg::dml(ggobj = nFeature_violin)
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_right())
  
  
  
  nCount_title <- paste0('Pre-Filter UMIs Per Nucleus','\n','cut-offs ',nCount_low,'-',nCount_high)
  nCount_violin <- QC_Plots_UMIs(seurat_object = seurat_merged, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nCount_title)
  vectorized_plot <- rvg::dml(ggobj = nCount_violin)
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_left())
  
  nCount_title <- paste0('Post-Filter UMIs Per Nucleus','\n','cut-offs ',nCount_low,'-',nCount_high)
  nCount_violin <- QC_Plots_UMIs(seurat_object = seurat_filtered, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nCount_title)
  vectorized_plot <- rvg::dml(ggobj = nCount_violin)
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_right())
  
  
  
  complexity_title <- paste0('Pre-Filter Cell Complexity','\n','complexity threshold ',complexity_cutoff)
  complexity_violin <- QC_Plots_Complexity(seurat_object = seurat_merged, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = complexity_title)
  vectorized_plot <- rvg::dml(ggobj = complexity_violin)
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_left())
  
  
  complexity_title <- paste0('Post-Filter Cell Complexity','\n','complexity threshold ',complexity_cutoff)
  complexity_violin <- QC_Plots_Complexity(seurat_object = seurat_filtered, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = complexity_title)
  vectorized_plot <- rvg::dml(ggobj = complexity_violin)
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_right())
  
  
  ## I didn't vectorize this plot because it would probably crash PowerPoint if it had to store position info
  ##    for 100,000+ dots. Because of this, I also put the pre- and post-filter UMIvsGene plots on separate slides
  ##    to maximize the resolution of the exported images.
  UMIvsGene_Plot <- QC_Plot_UMIvsGene(seurat_object = seurat_merged,high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
                                      high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")
  UMIvsGene_Plot + ggtitle('Pre-Filter Genes vs UMIs per Nucleus')
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = UMIvsGene_Plot, ph_location_fullsize())
  
  UMIvsGene_Plot <- QC_Plot_UMIvsGene(seurat_object = seurat_filtered, high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
                                      high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")
  UMIvsGene_Plot + ggtitle('Post-Filter Genes vs UMIs per Nucleus')
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = UMIvsGene_Plot, ph_location_fullsize())
  

  save_filename <- paste0(figure_dir,'/',data_prefix,'_QC_BasicMetricPlots.pptx')
  print(figures_PP, target = save_filename)
  rm(figures_PP)
  

}


############################################
###################
##
##    Save a copy of the filtered seurat object

if (save_seurat_objects) {  
  saveRDS(seurat_filtered , file = paste0(data_output_dir,"/seurat_filtered_",data_prefix,".rds"))
}







########################################################################
##
##  STEP2: Run Doublet Removal
##
########################################################################

## The following chunk of code will run doublet finder to identify doublets in the seurat_filtered
##    object and remove them. The doublet finder function requires a number of variables,
##    the most important of which is the expected number of real doublets in your data. The function
##    will basically find as many doublets as you tell it to.
## Conveniently, Ashley has this function set up to automatically calculate values for the key variables
##    needed to run doublet finder based on the dataset it is analyzing. The one exception is the
##    expected percent of doublets, which needs to be determined by the user and dfined using the
##    Expected_Pct_Doublets variable below.

if (run_doublet_finder) {
  
  Expected_Pct_Doublets <- 0.1
  
  ## pN: the number of artificial doublets, represented as a fraction 
  ## pK: the neighorhood size used to compute the number of artifical nearest neighbors
  ## Exp: the number of expected real doublets
  ## Pre-process Seurat object (standard) ------------------------------------------------------
  # Perform Seurat preprocessing on Merged plate1 seurat object.  
  
  ## Seurat objects need to be fully pre-processed prior to doublet removal. However,
  ##    this pre-processing is performed within the loop below so it does not need to be completed
  ##    prior to feeding the seurat_filtered object into the following chunk of code.
  
  set.seed(100)
  
  seurat.list <- SplitObject(seurat_filtered, split.by = "orig.ident") #or try by sublibrary
  #length(seurat.list)
  
  #names(seurat.list)
  #length(seurat.list)
  
  # loop through samples to find doublets
  for (i in 1:length(seurat.list)) {
    # print the sample we are on
    print(paste0("Sample ",i, " of ", length(seurat.list)))
    
    # Pre-process seurat object with standard seurat workflow
    sample <- NormalizeData(seurat.list[[i]])
    sample <- FindVariableFeatures(sample, nfeatures = nVariableFeatures)
    sample <- ScaleData(sample)
    sample <- RunPCA(sample)
    
    ## The following code attempts to mathematically determine the appropriate number
    ##    of principle components to use in subsequent functions that use PCA dimensional
    ##    reduction data as input.
    if (use_automated_nPCs_calc) {
      stdv <- sample[["pca"]]@stdev
      sum.stdv <- sum(sample[["pca"]]@stdev)
      percent.stdv <- (stdv / sum.stdv) * 100
      cumulative <- cumsum(percent.stdv)
      co1 <- which(cumulative > PCs_CumulPctVar_Threshold & percent.stdv < PCs_AbsVar_Threshold)[1]
      co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                           percent.stdv[2:length(percent.stdv)]) > PC_DeltaVar_Threshold), 
                  decreasing = T)[1] + 1
      nPCs_for_cluster_fxns <- min(co1, co2)
      nPCs_for_cluster_tracker <- c(nPCs_for_cluster_tracker,paste0('DoubletFinder - ',sublibrary_IDs[i],' nPCs = ',as.character(nPCs_for_cluster_fxns)))
    }

    # finish pre-processing
    sample <- FindNeighbors(object = sample, dims = 1:nPCs_for_cluster_fxns)              
    sample <- FindClusters(object = sample)
    ## sample <- RunUMAP(sample, dims = 1:20) ## Doublet finder appears to use tSNE, not UMAP,
    ##                                           so I'm removing this step to speed up the code
    sample <- RunTSNE(sample, assay = "RNA")
    # Find significant PCs

    #nPCs_for_cluster_fxns
    
    # pK identification (no ground-truth)
    sweep.list <- paramSweep(sample, PCs = 1:nPCs_for_cluster_fxns)
    sweep.stats <- summarizeSweep(sweep.list)
    bcmvn <- find.pK(sweep.stats)
    
    # Optimal pK is the max of the bomodality coefficent (BCmvn) distribution
    bcmvn.max <- bcmvn[which.max(bcmvn$BCmetric),]
    optimal.pk <- bcmvn.max$pK
    optimal.pk <- as.numeric(levels(optimal.pk))[optimal.pk]
    
    ## Homotypic doublet proportion estimate
    annotations <- sample@meta.data$seurat_clusters
    homotypic.prop <- modelHomotypic(annotations) 
    nExp.poi <- round(Expected_Pct_Doublets*nrow(sample@meta.data)) 
    nExp.poi.adj <- round(nExp.poi * (1 - homotypic.prop))
    
    sample <- RunTSNE(sample)
    # run DoubletFinder
    sample <- doubletFinder(seu = sample, 
                            PCs = 1:nPCs_for_cluster_fxns, 
                            pK = optimal.pk,
                            nExp = nExp.poi.adj)
    metadata <- sample@meta.data
    
    ## If you've copied this function from another version of this code and it isn't working
    ##    properly on your multi-assay seurat object, it is because you need to update the
    ##    line of code below.
    colnames(metadata)[ncol(metadata)] <- "doublet_finder"
    sample@meta.data <- metadata
    
    #save doublet identity in seurat metadata
    seurat.list[[i]] <- sample
    remove(sample)
  }
  rm(sweep.list)
  
  
  ##############################################
  ##
  ##  Doublet finder loop complete. Merging processed seurat objects.
  ##
  
  ## Merge_Seurat_List is convenient, but it appears to automatically attempt to append tags from
  ##    the add.cell.ids option. If you leave that option empty, the merge will work fine, but all your
  ##    cell names will end up with a "_" at the beginning (i.e., it doesn't add any cell ID tags, but
  ##    it still adds the spacer between the non-existant cell ID tag and the original cell name)
  seurat.doubletfinder <- merge(seurat.list[[1]], y = unlist(seurat.list[2:length(seurat.list)]))
  rm(seurat.list)
  
  
  ##########################################
  ##
  ## Removing unnecessary metadata
  ##
  
  ## Doublet finder produces two columns of data for each processed sublibrary. One named
  ##    doublet_finder (we actually define the name of this variable in the code above) that
  ##    contains the Singlet or Doublet classification for each cell. And another column called
  ##    "pANN_[bunch of numbers]" that contains the value of the metric doublet finder uses to
  ##    identify doublets. 
  ## We are only interested in the Singlet vs Doublet classification produced by doublet finder.
  ##    So, to clean up the resulting meta.data, the following code will remove the "pANN_..."
  ##    columns.
  
  metadata <- seurat.doubletfinder@meta.data
  gratuitous_metadata <- grep('pANN',colnames(metadata))
  metadata <- metadata[,-gratuitous_metadata]
  seurat.doubletfinder@meta.data <- metadata 
  
  
  
  #############################
  ##
  ##  Update the filtering_stats tracker
  ##  Add information on the number of doublets identified to the filtering stats tracking data frame
  ##
  
  doublet_finder_stats <- data.frame(matrix(nrow=2,ncol=(length(sublibrary_IDs)+1)))
  colnames(doublet_finder_stats) <- c('Metric',sublibrary_IDs)
  doublet_finder_stats$Metric[1] <- 'Doublets_Identified'
  doublet_finder_stats$Metric[2] <- 'nCells_Singlets'
  
  for (i in 1:length(sublibrary_IDs)) {
    doublet_finder_results <- as.data.frame(table(seurat.doubletfinder$doublet_finder[seurat.doubletfinder$orig.ident==sublibrary_IDs[i]]))
    doublet_finder_stats[,(i+1)] <- doublet_finder_results$Freq
  }
  
  doublet_finder_stats$Totals <- rowSums(doublet_finder_stats[,c(2:ncol(doublet_finder_stats))])
  #filtering_stats <- rbind(filtering_stats, doublet_finder_stats)
  
  metadata <- seurat.doubletfinder@meta.data
  
  for (x in 2:length(Seurat::Assays(seurat.doubletfinder))) {
    assay_name <- Seurat::Assays(object = seurat.doubletfinder)[x]
    serotype <- str_split(assay_name, pattern = "_")[[1]][1]
    metadata_column_name <- paste0(serotype,'_transduction')
    assay_stats <- data.frame(matrix(nrow=1,ncol=ncol(doublet_finder_stats)))
    colnames(assay_stats) <- colnames(doublet_finder_stats)
    assay_stats$Metric[1] <- paste0(serotype,'_Doublets')

    for (i in 1:length(sublibrary_IDs)) {
      metadata_pull <- metadata[metadata$orig.ident == sublibrary_IDs[i],]
      metadata_pull <- metadata_pull[metadata_pull$doublet_finder == 'Doublet',]
      assay_stats[1,i+1] <-  sum(metadata_pull[,metadata_column_name] == TRUE)
    }
    assay_stats$Totals <- rowSums(assay_stats[,c(2:(ncol(assay_stats)-1))])
    doublet_finder_stats <- rbind(doublet_finder_stats,assay_stats)
  }
  
  
  
  ###################################
  ##
  ##  Doublet finder QC plots
  ##  
  ###################################
  
  ################################
  ##
  ##  Basic QC Plots
  ##
  
  ## Visualize QC Data for Doublets vs Singlets
  ## Note: The figures created by the following code are meant to be viewed in R. There is code
  ##    after this section that will create and save copies of these figures to a PowerPoint file.
  
  DoubletViolinPlots <- VlnPlot(seurat.doubletfinder, features = c("nFeature_RNA", "nCount_RNA","percent_mito"), group.by = "doublet_finder", log = TRUE, pt.size = 0, combine=FALSE) 
  Doublet_nFeature <- DoubletViolinPlots[[1]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white')
  Doublet_nCount <- DoubletViolinPlots[[2]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white')
  Doublet_nMito <- DoubletViolinPlots[[3]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white')
  wrap_plots(Doublet_nFeature, Doublet_nCount, Doublet_nMito, ncol = 3)
  
  
  
  
  ################################
  ##
  ##  Dimensionality Reduction and Feature Mapping Plots
  ##
  
  ## Prior to plotting dimensionality reductions and related plots, we need to run seurat.doubletfinder
  ##    through the standard seurat workflow.
  ## Note: this is a slight alteration of the standard workflow because it is using 3500
  ##    features as the value for FindVariableFeatures instead of 2000 which is the default.
  ##    The Seurat documentation suggests that generally more is better as far as nfeatures goes.
  ##    The reason for this is that higher numbers of nfeatures allow better estimates of the
  ##    variance calculations associated with dimensionality reductions, specifically PCAs in this case.
  
  Idents(seurat.doubletfinder) <- 'orig.ident'
  seurat.doubletfinder <- NormalizeData(object = seurat.doubletfinder) %>%
    FindVariableFeatures(nfeatures = nVariableFeatures) %>%
    ScaleData() %>%
    RunPCA()
  
  if (use_automated_nPCs_calc) {
    stdv <- seurat.doubletfinder[["pca"]]@stdev
    sum.stdv <- sum(seurat.doubletfinder[["pca"]]@stdev)
    percent.stdv <- (stdv / sum.stdv) * 100
    cumulative <- cumsum(percent.stdv)
    co1 <- which(cumulative > PCs_CumulPctVar_Threshold & percent.stdv < PCs_AbsVar_Threshold)[1]
    co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                         percent.stdv[2:length(percent.stdv)]) > PC_DeltaVar_Threshold), 
                decreasing = T)[1] + 1
    nPCs_for_cluster_fxns <- min(co1, co2)
    nPCs_for_cluster_tracker <- c(nPCs_for_cluster_tracker,paste0('seurat.doubletfinder nPCs = ',as.character(nPCs_for_cluster_fxns)))
  }
  
  seurat.doubletfinder <- seurat.doubletfinder %>%
    FindNeighbors(dims = 1:nPCs_for_cluster_fxns) %>%
    FindClusters(resolution = FindClusterResolution) %>%
    RunUMAP(dims = 1:nPCs_for_cluster_fxns)
  
  
  

  
  
  
  ## While interesting on their own, many of these dimensionality reduction plots are most
  ##    interesting in comparison to identical plots following removal of doublets. So, we are going to
  ##    create a new seurat object from just the singlets, run it through the standard seurat workflow,
  ##    and then use it for comparison.
  ## This isn't the most efficient use of resources because we are going to re-create and re-run the
  ##    seurat.singlets object later in the code as part of applying the Harmony package.
  
  Idents(seurat.doubletfinder) <- "doublet_finder"
  seurat.singlets <- subset(x = seurat.doubletfinder, idents = "Singlet")
  seurat.singlets <- NormalizeData(object = seurat.singlets) %>%
    FindVariableFeatures(nfeatures = nVariableFeatures) %>%
    ScaleData() %>%
    RunPCA()
  
  if (use_automated_nPCs_calc) {
    stdv <- seurat.singlets[["pca"]]@stdev
    sum.stdv <- sum(seurat.singlets[["pca"]]@stdev)
    percent.stdv <- (stdv / sum.stdv) * 100
    cumulative <- cumsum(percent.stdv)
    co1 <- which(cumulative > PCs_CumulPctVar_Threshold & percent.stdv < PCs_AbsVar_Threshold)[1]
    co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                         percent.stdv[2:length(percent.stdv)]) > PC_DeltaVar_Threshold), 
                decreasing = T)[1] + 1
    nPCs_for_cluster_fxns <- min(co1, co2)
    nPCs_for_cluster_tracker <- c(nPCs_for_cluster_tracker,paste0('seurat.singlets nPCs = ',as.character(nPCs_for_cluster_fxns)))
  }
  
  seurat.singlets <- seurat.singlets %>%
    FindNeighbors(dims = 1:nPCs_for_cluster_fxns) %>%
    FindClusters(resolution = FindClusterResolution) %>%
    RunUMAP(dims = 1:nPCs_for_cluster_fxns)
  
  
  ## This is the one UMAP showing a seurat.doubletfinder specific comparison. Namely, the distribution of
  ##    identified doublets and singlets within the UMAP.
  DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "doublet_finder", shuffle = TRUE) + labs(title='UMAP - Doublet vs Singlet')
  
  ## Clustering Pre- and Post-Doublet Filtering
  DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "seurat_clusters", shuffle = TRUE) + labs(title='Pre-Doublet Filter - Seurat Clusters')
  DimPlot(object = seurat.singlets, reduction = "umap", group.by = "seurat_clusters", shuffle = TRUE) + labs(title='Post-Doublet Filter - Seurat Clusters')
  
  ## Sublibrary Distribution Pre- and Post-Doublet Filtering
  DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "orig.ident", shuffle = TRUE) + labs(title='Pre-Doublet Filter - Sublibraries')
  DimPlot(object = seurat.singlets, reduction = "umap", group.by = "orig.ident", shuffle = TRUE) + labs(title='Post-Doublet Filter - Sublibraries')
  
  ## QC Feature Distribution Pre- and Post-Doublet Filtering
  FeaturePlot(seurat.doubletfinder, features = c("nFeature_RNA", "nCount_RNA","percent_mito"), cols=c('lightblue','red')) + plot_annotation(title = "Pre-Doublet Filter") & theme(plot.title = element_text(hjust = 0.5, size=18)) 
  FeaturePlot(seurat.singlets, features = c("nFeature_RNA", "nCount_RNA","percent_mito"), cols=c('lightblue','red')) + plot_annotation(title = "Post-Doublet Filter") & theme(plot.title = element_text(hjust = 0.5, size=18)) 
  
  ## If you are curious about the distribution of transduced cells you can run the following code. 
  ##    I've commented these plots out because I've hard-coded the serotype IDs in here. 
  ##    I figure it's not worth coding these in as variables given that this is really
  ##    just 'look and see' code.
  #DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "AAV2_transduction")
  #DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "AAV9_transduction")
  
  
  

  ####################
  ######################################
  ##
  ##  Create and save a PowerPoint file containing QC plots and UMAPs associated with the
  ##    doublet finder data.
  ##
  
  if (save_figures) {
    
    figures_PP <- read_pptx()
    windowsFonts("Times" = windowsFont("Times"))
    text_mod <- fp_text_lite(font.size=22, color='black')
    
    
    DoubletViolinPlots <- VlnPlot(seurat.doubletfinder, features = c("nFeature_RNA", "nCount_RNA", "percent_mito"), group.by = "doublet_finder", log = TRUE, pt.size = 0, combine=FALSE) 
    Doublet_nFeature <- DoubletViolinPlots[[1]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white') + labs(title='Genes/Nucleus') + theme(axis.title.x = element_blank(), legend.position = "none") 
    Doublet_nCount <- DoubletViolinPlots[[2]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white') + labs(title='UMIs/Nucleus') + theme(axis.title.x = element_blank(), legend.position = "none")
    
    Doublet_nMito <- DoubletViolinPlots[[3]] + geom_boxplot(outlier.shape=NA, width=.2, fill='white') + labs(title='log(%) Mito') + theme(axis.title.x = element_blank())
    Doublet_Plot <- wrap_plots(Doublet_nFeature, Doublet_nCount, Doublet_nMito, ncol = 3)
    
    doublet_plot_title <- paste0('QC Metrics - Doublets vs Singlets')
    vectorized_plot <- rvg::dml(ggobj = Doublet_Plot)
    #properties1 <- fp_text(font.size = 14)
    slide_title <- fpar(ftext(doublet_plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_type(type = "body"))
    
    ## This is the one UMAP showing a seurat.doubletfinder specific comparison. Namely, the distribution of
    ##    identified doublets and singlets within the UMAP.
    doublet_vs_single_UMAP <- DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "doublet_finder", shuffle = TRUE) + labs(title='UMAP - Doublet vs Singlet')
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = doublet_vs_single_UMAP, ph_location_type(type = "body"))
    
    ## Clustering Pre- and Post-Doublet Filtering
    PreFilter_UMAP_Seurat_Clusters <- DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "seurat_clusters", shuffle = TRUE) + labs(title='Pre-Doublet Filter - Seurat Clusters')
    PostFilter_UMAP_Seurat_Clusters <- DimPlot(object = seurat.singlets, reduction = "umap", group.by = "seurat_clusters", shuffle = TRUE) + labs(title='Post-Doublet Filter - Seurat Clusters')
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = PreFilter_UMAP_Seurat_Clusters, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = PostFilter_UMAP_Seurat_Clusters, ph_location_right())
    
    ## Sublibrary Distribution Pre- and Post-Doublet Filtering
    PreFilter_UMAP_Sublibraries <- DimPlot(object = seurat.doubletfinder, reduction = "umap", group.by = "orig.ident", shuffle = TRUE) + labs(title='Pre-Doublet Filter - Sublibrary Comparison')
    PostFilter_UMAP_Sublibraries <- DimPlot(object = seurat.singlets, reduction = "umap", group.by = "orig.ident", shuffle = TRUE) + labs(title='Post-Doublet Filter - Sublibrary Comparison')
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = PreFilter_UMAP_Sublibraries, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = PostFilter_UMAP_Sublibraries, ph_location_right())
    
    ## QC Feature Distribution Pre- and Post-Doublet Filtering
    PreFilter_FeaturePlots <- FeaturePlot(seurat.doubletfinder, features = c("nFeature_RNA", "nCount_RNA","percent_mito"), cols=c('lightblue','red')) + plot_annotation(title = "Pre-Doublet Filter") & theme(plot.title = element_text(hjust = 0.5, size=18)) 
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = PreFilter_FeaturePlots, ph_location_type(type = "body"))
    
    PostFilter_FeaturePlots <- FeaturePlot(seurat.singlets, features = c("nFeature_RNA", "nCount_RNA","percent_mito"), cols=c('lightblue','red')) + plot_annotation(title = "Post-Doublet Filter") & theme(plot.title = element_text(hjust = 0.5, size=18)) 
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = PostFilter_FeaturePlots, ph_location_type(type = "body"))
    

    save_filename <- paste0(figure_dir,'/',data_prefix,'_DoubletFinder_Results.pptx')
    print(figures_PP, target = save_filename)
    rm(figures_PP)
    
  }
  
  
  
  ##############
  ######################################
  ##
  ##  Save the DoubletFinder seurat object
  
  if (save_seurat_objects) {  
    saveRDS(seurat.doubletfinder , file = paste0(data_output_dir,"/seurat.doubletfinder_",data_prefix,".rds"))
  }
  
  ## We are going to re-create this seurat object below using a different name, so we don't need this copy anymore.
  ##    It's admittedly inefficient to re-subset the seurat.doubletfinder object, but it makes the distinction between the
  ##    different sections of the code a little cleaner.
  rm(seurat.singlets)
  
}





#####################################
##################################################################
##
##  Prepare for Final Seurat Object Creation and Processing
##
##################################################################
#####################################

## We're going to create a new seurat object here called seurat_integrations to run the final
##    processing on. It's a little gratuitous to create a new seurat object here, but it makes the rest of
##    the code a bit cleaner and keeps a clean copy of your current seurat object that you can return to
##    if necessary.

if (run_doublet_finder) {
  Idents(seurat.doubletfinder) <- "doublet_finder"
  seurat_integrations <- subset(x = seurat.doubletfinder, idents = "Singlet")
  
  ## Note: 03/2024 - Something happens to the seurat object during processing by
  ##    doublet finder that causes later code calculating RPCA integrations to fail.
  ## I tried to fix the issue in a bunch of different ways, but ultimately they all failed.
  ##    The error message indicates that the problem is some bug with how the IntegrateLayers function
  ##    is identifying the data it should be feeding to some of the 'behind the scenes' functions
  ##    involved in running the RPCA methodology.
  ## Anyhow, the only way I could fix the problem was by removing all previous normalization and
  ##    scaling data from the seurat object, which itself is a huge pain because the function
  ##    that is supposed to enable that (DietSeurat) has a known bug and is currently broken.
  ##    So, I wrote my own code to do it. 
  ## Once you run this code to remove all the non-'counts' layers, it no longer returns the RPCA IntegrateLayers error.
  
  layers_to_remove <- Layers(seurat_integrations)[grep("counts",Layers(seurat_integrations), invert = TRUE)]
  for (i in 1:length(layers_to_remove)) {
    seurat_integrations[['RNA']][layers_to_remove[i]] <- NULL
  }

  ## Diet Seurat is currently broken
  #layers_to_keep <- Layers(seurat_integrations)[grep("counts",Layers(seurat_integrations))]
  #seurat_integrations <- DietSeurat(object = seurat_integrations,
  #                                  layers = layers_to_keep,
  #                                  assays = c(Seurat::Assays(seurat_integrations)))
  
} else {
  seurat_integrations <- seurat_filtered
}



###################################
## Running (or re-running depending on how you've run the code) the basic
##    Seurat workflow

seurat_integrations <- seurat_integrations %>%
  NormalizeData() %>%
  FindVariableFeatures(nfeatures = nVariableFeatures)

## Removing mitochondrial genes from the list of variable features
VariableFeatures(seurat_integrations) <- VariableFeatures(seurat_integrations)[!grepl("(?i)^mt-", VariableFeatures(seurat_integrations))]

seurat_integrations <- seurat_integrations %>%
  ScaleData(vars.to.regress = variables_to_regress) %>%
  RunPCA()
  
if (use_automated_nPCs_calc) {
  stdv <- seurat_integrations[["pca"]]@stdev
  sum.stdv <- sum(seurat_integrations[["pca"]]@stdev)
  percent.stdv <- (stdv / sum.stdv) * 100
  cumulative <- cumsum(percent.stdv)
  co1 <- which(cumulative > PCs_CumulPctVar_Threshold & percent.stdv < PCs_AbsVar_Threshold)[1]
  co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                       percent.stdv[2:length(percent.stdv)]) > PC_DeltaVar_Threshold), 
              decreasing = T)[1] + 1
  nPCs_for_cluster_fxns <- min(co1, co2)
  nPCs_for_cluster_tracker <- c(nPCs_for_cluster_tracker,paste0('seurat_integrations nPCs = ',as.character(nPCs_for_cluster_fxns)))
}
  
seurat_integrations <- seurat_integrations %>%
  FindNeighbors(reduction = "pca", dims=1:nPCs_for_cluster_fxns) %>%
  FindClusters(resolution = FindClusterResolution, cluster.name = "unintegrated_clusters") %>%
  RunUMAP(dims = 1:nPCs_for_cluster_fxns, reduction = "pca", reduction.name = "umap_unintegrated")


##################################
##
## Generating Plots based on the unintegrated PCA data

unintegrated_sublib_plot <- DimPlot(
  seurat_integrations,
  reduction = "umap_unintegrated",
  group.by = c("orig.ident"),
  combine = FALSE, label.size = 2, shuffle = TRUE
)
unintegrated_sublib_plot <- unintegrated_sublib_plot[[1]] + labs(title = "PCA") +
  xlab('UMAP_PC1') + ylab('UMAP_PC2') + 
  theme(legend.position = "bottom")
# + theme(legend.position = "none")

unintegrated_cluster_plot <- DimPlot(
  seurat_integrations,
  reduction = "umap_unintegrated",
  group.by = c("unintegrated_clusters"),
  combine = FALSE, label.size = 2, shuffle = TRUE
)
unintegrated_cluster_plot <- unintegrated_cluster_plot[[1]] + labs(title = "PCA") +
  xlab('UMAP_PC1') + ylab('UMAP_PC2') + theme(legend.position = "bottom")





#####################################
##################################################################
##
##  Run Integrations
##  
##  Currently the code is set up to run RPCA and Harmony integration
##
##################################################################
#####################################
  
  ## The general goal of integration is to take data from, e.g., two experimental conditions, and align it 
  ##    so that cells from the same cell type/subpopulation will cluster together. In other words, the goal is
  ##    to go from having two clusters [Condition 1 - Cell Type A] and [Condition 2 - Cell Type A] to having
  ##    a single cluster [Cell Type A] without discarding any of the information that distinguishes Condition 1
  ##    from Condition 2.
  
  ## From the Seurat Vignette: "We often refer to this procedure as intergration/alignment. When aligning 
  ##    two genome sequences together, identification of shared/homologous regions can help to interpret differences 
  ##    between the sequences as well. Similarly for scRNA-seq integration, our goal is not to remove biological 
  ##    differences across conditions, but to learn shared cell types/states in an initial step - specifically because 
  ##    that will enable us to compare control stimulated and control profiles for these individual cell types.
  
  ## The Seurat v5 integration procedure aims to return a single dimensional reduction that captures the shared 
  ##    sources of variance across multiple layers, so that cells in a similar biological state will cluster. The 
  ##    method returns a dimensional reduction (i.e. integrated.cca) which can be used for visualization and
  ##    unsupervised clustering analysis.
  
  
if (run_integrations) {
  
  ###################################
  ##
  ## Running RPCA Integration for comparison with results from standard workflow
  
  Idents(seurat_integrations) <- 'orig.ident'
  seurat_integrations <- IntegrateLayers(
    object = seurat_integrations, method = RPCAIntegration, assay = 'RNA',
    orig.reduction = "pca", new.reduction = "integrated.rpca", dims=1:nPCs_for_cluster_fxns,
    verbose = FALSE
  )
  
  seurat_integrations <- FindNeighbors(seurat_integrations, reduction = "integrated.rpca", dims = 1:nPCs_for_cluster_fxns)
  seurat_integrations <- FindClusters(seurat_integrations, resolution = FindClusterResolution, cluster.name = "rpca_clusters")
  seurat_integrations <- RunUMAP(seurat_integrations, reduction = "integrated.rpca", dims = 1:nPCs_for_cluster_fxns, reduction.name = "umap.rpca")
  
  ###################################
  ##
  ## Running Harmony Integration for comparison with results from standard workflow
  
  seurat_integrations <- IntegrateLayers(
    object = seurat_integrations, method = HarmonyIntegration,
    orig.reduction = "pca", new.reduction = "harmony",
    verbose = FALSE
  )
  
  seurat_integrations <- FindNeighbors(seurat_integrations, reduction = "harmony", dims = 1:nPCs_for_cluster_fxns)
  seurat_integrations <- FindClusters(seurat_integrations, resolution = FindClusterResolution, cluster.name = "harmony_clusters")
  seurat_integrations <- RunUMAP(seurat_integrations, reduction = "harmony", dims = 1:nPCs_for_cluster_fxns, reduction.name = "umap.harmony")
  
  
  ###################################
  ##
  ## Creating plots to for RPCA and Harmony Integrations
  ##
  
  rpca_sublib_plot <- DimPlot(
    seurat_integrations,
    reduction = "umap.rpca",
    group.by = c("orig.ident"),
    combine = FALSE, label.size = 2, shuffle = TRUE
  )
  rpca_sublib_plot <- rpca_sublib_plot[[1]] + labs(title = "RPCA_Integration") +
    xlab('UMAP_PC1') + ylab('UMAP_PC2') + theme(legend.position = "bottom")
  
  rpca_cluster_plot <- DimPlot(
    seurat_integrations,
    reduction = "umap.rpca",
    group.by = c("rpca_clusters"),
    combine = FALSE, label.size = 2, shuffle = TRUE
  )
  rpca_cluster_plot <- rpca_cluster_plot[[1]] + labs(title = "RPCA_Integration") +
    xlab('UMAP_PC1') + ylab('UMAP_PC2') + theme(legend.position = "bottom")
  
  
  harmony_sublib_plot <- DimPlot(
    seurat_integrations,
    reduction = "umap.harmony",
    group.by = c("orig.ident"),
    combine = FALSE, label.size = 2, shuffle = TRUE
  )
  harmony_sublib_plot <- harmony_sublib_plot[[1]] + labs(title = "Harmony_Integration") +
    xlab('UMAP_PC1') + ylab('UMAP_PC2') + theme(legend.position = "bottom")
  
  harmony_cluster_plot <- DimPlot(
    seurat_integrations,
    reduction = "umap.harmony",
    group.by = c("harmony_clusters"),
    combine = FALSE, label.size = 2, shuffle = TRUE
  )
  harmony_cluster_plot <- harmony_cluster_plot[[1]] + labs(title = "Harmony_Integration") +
    xlab('UMAP_PC1') + ylab('UMAP_PC2') + theme(legend.position = "bottom")
  
  
  ########################
  ##
  ## Check out the results in the R console
  
  wrap_plots(unintegrated_sublib_plot, rpca_sublib_plot, ncol = 2, byrow = F)
  wrap_plots(unintegrated_sublib_plot, harmony_sublib_plot, ncol = 2, byrow = F)
  wrap_plots(rpca_sublib_plot, harmony_sublib_plot, ncol = 2, byrow = F)
  
  wrap_plots(unintegrated_cluster_plot, rpca_cluster_plot, ncol = 2, byrow = F)
  wrap_plots(unintegrated_cluster_plot, harmony_cluster_plot, ncol = 2, byrow = F)
  wrap_plots(rpca_cluster_plot, harmony_cluster_plot, ncol = 2, byrow = F)
  
  
  
  ####################
  ######################################
  ##
  ##  Create and save a PowerPoint file containing QC plots and UMAPs associated with the
  ##    rpca and harmony integrations
  ##
  ##  NOTE - Most of the ggplots that will be saved in the following code block were created
  ##         in the chunk of code above this section.
  
  if (save_figures) {
    
    figures_PP <- read_pptx()
    windowsFonts("Times" = windowsFont("Times"))
    text_mod <- fp_text_lite(font.size=22, color='black')
    
  
    plot_title <- paste0('Unintegrated Data vs RPCA Integrated Data - Sublibrary Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = unintegrated_sublib_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = rpca_sublib_plot, ph_location_right())
    
    
    plot_title <- paste0('Unintegrated Data vs RPCA Integrated Data - Cluster Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = unintegrated_cluster_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = rpca_cluster_plot, ph_location_right())
    
    
    plot_title <- paste0('Unintegrated Data vs Harmony Integrated Data - Sublibrary Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = unintegrated_sublib_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = harmony_sublib_plot, ph_location_right())
    
    
    plot_title <- paste0('Unintegrated Data vs Harmony Integrated Data - Cluster Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = unintegrated_cluster_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = harmony_cluster_plot, ph_location_right())
    
    
    plot_title <- paste0('RPCA vs Harmony Integrated Data - Sublibrary Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = rpca_sublib_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = harmony_sublib_plot, ph_location_right())
    
    
    plot_title <- paste0('RPCA vs Harmony Integrated Data - Cluster Comparison')
    slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = rpca_cluster_plot, ph_location_left())
    figures_PP <- ph_with(figures_PP, value = harmony_cluster_plot, ph_location_right())
    
    Idents(seurat_integrations) <- "seurat_clusters"
    for (i in 2:length(Seurat::Assays(seurat_integrations))) {
      
      assay_name <- Seurat::Assays(object = seurat_integrations)[i]
      serotype <- str_split(assay_name,pattern='_')[[1]][1]
      AAV_metric <- paste0(serotype,'_transduction')
      
      transduction_plot <- DimPlot(object = seurat_integrations, reduction = "umap", split.by = AAV_metric) +
        plot_annotation(title = paste0(serotype," Transduction Status")) & theme(plot.title = element_text(hjust = 0.5, size=18))
      
      slide_title <- paste0('PCA UMAP Split by ',serotype,' Transduction Status')
      slide_title <- fpar(ftext(slide_title, text_mod), fp_p = fp_par(text.align = 'center'))
      figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
      figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
      figures_PP <- ph_with(figures_PP, value = transduction_plot, ph_location_type(type = "body"))
      
    }
    
    
    save_filename <- paste0(figure_dir,'/',data_prefix,'_IntegrationComp_Results.pptx')
    print(figures_PP, target = save_filename)
    rm(figures_PP)

  }
  
  
}  
  




########################################
##
## Saving the integrated seurat object
##

seurat_integrations <- JoinLayers(seurat_integrations)

if (save_seurat_objects) {  
  saveRDS(seurat_integrations, file = paste0(data_output_dir,"/seurat_integrations_",data_prefix,".rds"))
}




########################################
########################################
##
## Creating a PowerPoint File of Summary Figures of the Final Seurat Object
##


if (save_figures) {
  
  figures_PP <- read_pptx()
  windowsFonts("Times" = windowsFont("Times"))
  text_mod <- fp_text_lite(font.size=22, color='black')
  
  nFeature_title <- paste0('Genes Per Nucleus','\n','cut-offs ',nFeature_low,'-',nFeature_high)
  nFeature_violin <- QC_Plots_Genes(seurat_object = seurat_integrations, low_cutoff = nFeature_low, high_cutoff = nFeature_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nFeature_title)
  vectorized_plot <- rvg::dml(ggobj = nFeature_violin)
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_left())
  
  nCount_title <- paste0('UMIs Per Nucleus','\n','cut-offs ',nCount_low,'-',nCount_high)
  nCount_violin <- QC_Plots_UMIs(seurat_object = seurat_integrations, low_cutoff = nCount_low, high_cutoff = nCount_high, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = nCount_title)
  vectorized_plot <- rvg::dml(ggobj = nCount_violin)
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_right())
  
  complexity_title <- paste0('Cell Complexity','\n','complexity threshold ',complexity_cutoff)
  complexity_violin <- QC_Plots_Complexity(seurat_object = seurat_integrations, high_cutoff = complexity_cutoff, group.by = "orig.ident", y_axis_log = TRUE, pt.size = 0, plot_title = complexity_title)
  vectorized_plot <- rvg::dml(ggobj = complexity_violin)
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = vectorized_plot, ph_location_type(type = "body"))
  

  UMIvsGene_Plot <- QC_Plot_UMIvsGene(seurat_object = seurat_integrations,high_cutoff_gene = nFeature_high,low_cutoff_gene = nFeature_low,
                                      high_cutoff_UMI = nCount_high, low_cutoff_UMI = nCount_low, group.by = "orig.ident")
  UMIvsGene_Plot + ggtitle('Genes vs UMIs per Nucleus')
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = UMIvsGene_Plot, ph_location_fullsize())
  
  
  plot_title <- paste0('Final STEP2 Seurat - Sublibrary Comparison - PCA')
  slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
  figures_PP <- ph_with(figures_PP, value = unintegrated_sublib_plot, ph_location_type(type = "body"))

  
  plot_title <- paste0('Final STEP2 Seurat - Cluster Comparison - PCA')
  slide_title <- fpar(ftext(plot_title, text_mod), fp_p = fp_par(text.align = 'center'))
  figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
  figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
  figures_PP <- ph_with(figures_PP, value = unintegrated_cluster_plot, ph_location_type(type = "body"))

  
  Idents(seurat_integrations) <- "seurat_clusters"
  for (i in 2:length(Seurat::Assays(seurat_integrations))) {
    
    assay_name <- Seurat::Assays(object = seurat_integrations)[i]
    serotype <- str_split(assay_name,pattern='_')[[1]][1]
    AAV_metric <- paste0(serotype,'_transduction')
    
    transduction_plot <- DimPlot(object = seurat_integrations, reduction = "umap_unintegrated", split.by = AAV_metric) +
      plot_annotation(title = paste0(serotype," Transduction Status")) & theme(plot.title = element_text(hjust = 0.5, size=18))
    
    slide_title <- paste0('PCA UMAP Split by ',serotype,' Transduction Status')
    slide_title <- fpar(ftext(slide_title, text_mod), fp_p = fp_par(text.align = 'center'))
    figures_PP <- add_slide(figures_PP,layout = "Title and Content", master = "Office Theme")
    figures_PP <- ph_with(figures_PP, value = slide_title, location = ph_location_type(type = "title"))
    figures_PP <- ph_with(figures_PP, value = transduction_plot, ph_location_type(type = "body"))
    
  }
  
  save_filename <- paste0(figure_dir,'/',data_prefix,'_FinalSeurat_SummaryFigures.pptx')
  print(figures_PP, target = save_filename)
  rm(figures_PP)
  
}



########################################
########################################
##
##  Calculating Basic Stats on the Final Seurat Object
##
##  These are only used for the RunInfoAndStats output text file


final_cell_counts <- as.data.frame(table(seurat_integrations$orig.ident))
final_seurat_object_stats <- data.frame(matrix(nrow=1,ncol=(length(sublibrary_IDs)+1)))
colnames(final_seurat_object_stats) <- c('Metric',sublibrary_IDs)
final_seurat_object_stats$Metric <- c('nCells')
for (i in 2:ncol(final_seurat_object_stats)) {
  final_seurat_object_stats[1,i] <- final_cell_counts[(i-1),2]
}
finalobject_metadata <- seurat_integrations@meta.data
for (x in 2:length(Seurat::Assays(seurat_integrations))) {
  assay_name <- Seurat::Assays(object = seurat_integrations)[x]
  serotype <- str_split(assay_name, pattern = "_")[[1]][1]
  metadata_column_name <- paste0(serotype,'_transduction')
  assay_stats <- data.frame(matrix(nrow=1,ncol=ncol(final_seurat_object_stats)))
  colnames(assay_stats) <- colnames(final_seurat_object_stats)
  assay_stats$Metric[1] <- paste0('nCell_',serotype)
  for (i in 1:length(sublibrary_IDs)) {
    finalobject_metadata_pull <- finalobject_metadata[finalobject_metadata$orig.ident == sublibrary_IDs[i],]
    assay_stats_sub <- as.data.frame(table(finalobject_metadata_pull[,metadata_column_name]))
    assay_stats[1,i+1] <- assay_stats_sub[2,2]
  }
  final_seurat_object_stats <- rbind(final_seurat_object_stats,assay_stats)
}
final_seurat_object_stats$Totals <- rowSums(final_seurat_object_stats[,c(2:ncol(final_seurat_object_stats))])




if (save_stat_tables) {
  
  STEP2_stat_tables <- list()
  STEP2_stat_tables[['artifact_filtering_stats']] <- artifact_filtering_stats
  STEP2_stat_tables[['QC_filtering_stats']] <- QC_filtering_stats
  if (run_doublet_finder) {
    STEP2_stat_tables[['doublet_finder_stats']] <- doublet_finder_stats
  }
  STEP2_stat_tables[['final_seurat_object_stats']] <- final_seurat_object_stats
  
  saveRDS(STEP2_stat_tables, file = paste0(data_output_dir,"/STEP2_StatsTables_",data_prefix,".rds"))
  
}

















thetime <- Sys.time()
Date_Tag <- paste0(substr(thetime,3,4),substr(thetime,6,7),substr(thetime,9,10),substr(thetime,8,8),
                   substr(thetime,12,13),'h',substr(thetime,15,16),'m')

Stat_Output_Filename <- paste0("RunInfoAndStats-STEP2-",data_prefix,"-",Date_Tag,".txt")
setwd(data_output_dir)

sink(file = Stat_Output_Filename)

print("STEP2_QC_Preprocessing_CombiningSublibraries.R")
print("Run on:")
Sys.time()
print("---------------------------------------------------------------------------------------------")
print(paste("Seurat Sublibrary Data Directory:",data_dir))
print("-------------------------------------")
print(paste("Seurat Sublibraries Loaded, Merged and Processed:"))
for (i in 1:length(files$name)) {
  print(as.character(files$name[i]))
}
print("---------------------------------------------------------------------------------------------")
print("General Code Option Settings")
print("----------------------------------------")
print(paste0("Tag for output file naming: data_prefix = ",data_prefix))
print(paste0("save_seurat_objects = ",save_seurat_objects))
print(paste0("Seurat Object Output Dir: ",data_output_dir))
print(paste0("save_figures = ",save_figures))
print(paste0("Summary Figures Output Dir: ",figure_dir))
print(paste0("save_stat_tables = ",save_stat_tables))
print("---------------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("--- GLOBAL SEURAT OBJECT PROCESSING SETTINGS ------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print(paste0("n Features used for FindVariableFeatures(): nVariableFeatures = ",as.character(nVariableFeatures)))
print(paste0("resolution value used for FindClusters(): FindClusterResolution = ",as.character(FindClusterResolution)))
print("----------------------------------------")
print("Automated Optimal PC Detection Settings:")
print("----------------------------------------")
print("If automated detection is turned on, optimal principle components for FindNeighbors(), RunTSNE(), and RunUMAP are calculated as the lesser of:")
print("A) The lowest PC that explains > PCs_CumulPctVar_Threshold % of the cumulative variance AND is followed by")
print("no PCs that explain > PCs_AbsVar_Threshold variance % variance")     
print("B) The lowest PC (+1) that is followed by no sequential PC pairs whose variance differs by more than PC_DeltaVar_Threshold %")
print("----------------------------")
print(paste0("use_automated_nPCs_calc = ",as.character(use_automated_nPCs_calc)))
if (use_automated_nPCs_calc) {
  print(paste0("PCs_CumulPctVar_Threshold = ",as.character(PCs_CumulPctVar_Threshold)))
  print(paste0("PCs_AbsVar_Threshold = ",as.character(PCs_AbsVar_Threshold)))
  print(paste0("PC_DeltaVar_Threshold = ",as.character(PC_DeltaVar_Threshold)))
} else {
  print(paste0("User Defined Optimal PCs: nPCs_for_cluster_fxns = ",as.character(nPCs_for_cluster_fxns)))
}
print("----------------------------")
print("------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("STEP 0 - PRE-PROCESSING - ARTIFACT CELL REMOVAL ---------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("------------------------------------------------------")
print("This pre-processing step identifies cells with barcodes that were not in the cell metadata file used")
print("to generate the seurat objects during STEP1 processing.")
print("------------------------------------------------------")
print("--- RESULTS ------------------------------------------")
print("------------------------------------------------------")
print(artifact_filtering_stats[c(1:3),])
for (i in 2:length(Seurat::Assays(seurat_integrations))) {
  print("-------------------------------------------------------------------------")
  print(paste0("Assay ",as.character(i-1),": ",Seurat::Assays(seurat_integrations)[i]))
  print(artifact_filtering_stats[c(((i-1)*3+1):((i-1)*3+3)),])
}
print("----------------------------")
print("------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("STEP 1 - INITIAL FILTERING OF LOW-QUALITY CELLS ---------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("------------------------------------------------------")
print("Filtering Parameters:")
print("--------------------------------------------------")
print("Gene Count Filters:")
print(paste0("nFeature_low = ",as.character(nFeature_low)))
print(paste0("nFeature_high = ",as.character(nFeature_high)))
print("------------------------")
print("UMI Count Filters:")
print(paste0("nCount_low = ",as.character(nCount_low)))
print(paste0("nCount_high = ",as.character(nCount_high)))
print("------------------------")
print("Complexity Filter:")
print(paste0("complexity_cutoff = ",as.character(complexity_cutoff)))
print("------------------------")
print("Mitochondrial Gene Percentage Filter:")
print(paste0("mito_threshold = ",as.character(mito_threshold)))
print("----------------------------")
print("------------------------------------------------------")
print("--- RESULTS ------------------------------------------")
print("------------------------------------------------------")
print(QC_filtering_stats[c(1:3),])
for (i in 2:length(Seurat::Assays(seurat_integrations))) {
  print("-------------------------------------------------------------------------")
  print(paste0("Assay ",as.character(i-1),": ",Seurat::Assays(seurat_integrations)[i]))
  print(QC_filtering_stats[c(((i-1)*3+1):((i-1)*3+3)),])
}
print("----------------------------")
print("------------------------------------------------------")
print("--- SAVED OUTPUTS ------------------------------------")
print("------------------------------------------------------")
print(paste0("save_seurat_objects = ",save_seurat_objects))
if (save_seurat_objects) {
  print(paste0("seurat_filtered Output File: ",paste0(data_output_dir,"/seurat_filtered_",data_prefix,".rds")))
}
print(paste0("save_figures = ",save_figures))
if (save_figures) {
  print(paste0("Summary Figures Output: ",paste0(figure_dir,'/',data_prefix,'_QC_BasicMetricPlots.pptx')))
}


print("----------------------------")
print("------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("STEP 2 - DOUBLET FINDER ---------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("------------------------------------------------------")
print(paste0("run_doublet_finder = ",as.character(run_doublet_finder)))
if (run_doublet_finder) {
  print(paste0("Expected_Pct_Doublets = ",as.character(Expected_Pct_Doublets)))
  print("----------------------------")
  print(paste0("use_automated_nPCs_calc = ",as.character(use_automated_nPCs_calc)))
  if (use_automated_nPCs_calc) {
    for (i in 1:length(sublibrary_IDs)) {
      print(nPCs_for_cluster_tracker[i])
    }
  } else {
    print(paste0("User Defined Optimal PCs: nPCs_for_cluster_fxns = ",as.character(nPCs_for_cluster_fxns)))
  }
  print("----------------------------")
  print("------------------------------------------------------")
  print("--- RESULTS ------------------------------------------")
  print("------------------------------------------------------")
  print(doublet_finder_stats)
  print("----------------------------")
  print("------------------------------------------------------")
  print("--- SAVED OUTPUTS ------------------------------------")
  print("------------------------------------------------------")
  print(paste0("save_seurat_objects = ",save_seurat_objects))
  if (save_seurat_objects) {
    print(paste0("seurat.doubletfinder Output File: ",paste0(data_output_dir,"/seurat.doubletfinder_",data_prefix,".rds")))
  }
  print("------------------------")
  print(paste0("save_figures = ",save_figures))
  if (save_figures) {
    print("Output figures include comparisons of PCA based UMAPs of seurat objects before and after doublet filtering.")
    print("Optimal PCs for the seurat.doubletfinder and seurat.singlets objects were calculated using:")
    print(paste0("use_automated_nPCs_calc = ",as.character(use_automated_nPCs_calc)))
    if (use_automated_nPCs_calc) {
      print(nPCs_for_cluster_tracker[grep("seurat.doubletfinder",nPCs_for_cluster_tracker)])
      print(nPCs_for_cluster_tracker[grep("seurat.singlets",nPCs_for_cluster_tracker)])
    } else {
      print(paste0("User Defined Optimal PCs: nPCs_for_cluster_fxns = ",as.character(nPCs_for_cluster_fxns)))
    }
    print("----------------------------")
    print(paste0("Summary Figures Output: ",paste0(figure_dir,'/',data_prefix,'_DoubletFinder_Results.pptx')))
  }
}

print("----------------------------")
print("------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("STEP 3 - FINAL SEURAT OBJECT PROCESSING -----------------------------------------------------")
print("---------------------------------------------------------------------------------------------")
print("------------------------------------------------------")
print("This section summarizes the variables used to process the final seurat object following")
print("artifact cell removal, QC metric filtering, and (optionally) doublet identification and removal")
print("---------------------------------------------------------------------------------------------")
print(paste0("nFeatures value in FindVariableFeatures() = ",as.character(nVariableFeatures)))
print(paste0("Variables regressed using ScaleData(): variables_to_regress = ",variables_to_regress))
print(paste0("PCs used for FindNeighbors() and RunUMAP():"))
print(paste0("use_automated_nPCs_calc = ",as.character(use_automated_nPCs_calc)))
if (use_automated_nPCs_calc) {
  print(nPCs_for_cluster_tracker[grep("seurat_integrations",nPCs_for_cluster_tracker)])
} else {
  print(paste0("User Defined Optimal PCs: nPCs_for_cluster_fxns = ",as.character(nPCs_for_cluster_fxns)))
}
print(paste0("resolution value used for FindClusters(): FindClusterResolution = ",as.character(FindClusterResolution)))
print("----------------------------")
print("------------------------------------------------------")
print("--- FINAL SEURAT OBJECT SUMMARY ----------------------")
print("------------------------------------------------------")
print(final_seurat_object_stats)
print("----------------------------")
print("------------------------------------------------------")
print("--- OPTIONAL INTEGRATIONS ----------------------------")
print("------------------------------------------------------")
print("The code is currently set up to perform optional integrations using RPCA and Harmony methods.")
print("Currently the code integrates over sublibrary ID. This feature could be expanded in the future if it proves useful.")
print("------------------")
print(paste0('run_integrations = ',as.character(run_integrations)))
if (run_integrations) {
  print(paste0("save_figures = ",save_figures))
  if (save_figures) {
    print(paste0("Summary Figures Output: ",paste0(figure_dir,'/',data_prefix,'_IntegrationComp_Results.pptx')))
  }
}
print("----------------------------")
print("------------------------------------------------------")
print("--- SAVED OUTPUTS ------------------------------------")
print("------------------------------------------------------")
print(paste0("save_seurat_objects = ",save_seurat_objects))
if (save_seurat_objects) {
  print(paste0("seurat_integrations Output File: ",paste0(data_output_dir,"/seurat_integrations_",data_prefix,".rds")))
}
print("------------------")
print(paste0("save_figures = ",save_figures))
if (save_figures) {
  print(paste0("Final Seurat Summary Figures Output: ",paste0(figure_dir,'/',data_prefix,'_FinalSeurat_SummaryFigures.pptx')))
}
print("------------------")
print(paste0("save_stat_tables = ",save_stat_tables))
if (save_stat_tables) {
  print(paste0("Stat Tables Output RDS: ",paste0(data_output_dir,"/STEP2_StatsTables_",data_prefix,".rds")))
}


sink(file = NULL)







